app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^shopcar/$', views.shopcar, name='shopcar'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^common/$', views.common, name='common'),
    url(r'^goods/(\d+)/$', views.goods, name='goods'),
    url(r'^goods2/$', views.goods2, name='goods2'),
    url(r'^CheckTel/$', views.CheckTel, name='CheckTel'),
    url(r'^AddToCart/$', views.AddToCart, name='AddToCart'),
    url(r'^click/$', views.click, name='click'),
    url(r'^remove/$', views.remove, name='remove'),
    url(r'^change/$', views.change, name='change'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^subcart/$', views.subcart, name='subcart'),
]

project18/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='app'))
]

templates/common.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title></title>
    <link rel="stylesheet" href="{% static 'css/common.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    {#    <script type="text/javascript" src="{% static 'js/test.js' %}"></script>#}
</head>
<body>
<!--头部开始-->
<div class="header">
    <div class="header_con">
        <div class="header_left">
		 			<span>
			 			<a href="#" class="header_a">E宠就是正品</a>
			 			<i>评价(<a href="#">389.4万</a>)</i>
		 		    </span>
        </div>
        <div class="header_right">
            <ul>
                <li><a href="#">[登录]</a></li>
                <li><a href="#">[注册]</a></li>
                <li><a href="#">购物车</a></li>
                <li id="mypet">
                    <a href="#">我的E宠<img src="{% static 'img/common_img/h5.gif' %}"></a>
                    <div class="mypet">
                        <a href="#">我的订单 </a>
                        <a href="#">充值得到优惠</a>
                        <a href="#">兑换现金劵</a>
                        <a href="#">推荐得惊喜</a>
                    </div>
                </li>
                <li>
                    <a href="#">收藏我 <img src="{% static 'img/common_img/h5.gif' %}"></a>
                    <div class="mycollect">
                        <input value="加入收藏夹" class="join" type="button">
                        <input value="保存到桌面" class="save" type="button">
                    </div>
                </li>
                <li><a href="#">手机版</a></li>
                <li><a href="#">帮助</a></li>
                <li><a href="#" class="lastli">投诉建议</a></li>
            </ul>
        </div>


    </div>
</div>
<!--头部结束-->
<!--尾部开始-->
<div class="footer">
    <div class="footer_top">
        <div class="top_list">
            <ul>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_03.gif' %}">
                    <p>绝对正品</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_05.gif' %}">
                    <p>全球的好货</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_07.gif' %}">
                    <p>自家的仓库</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_09.gif' %}">
                    <p>自家的配送</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_11.gif' %}">
                    <p>养宠的帮手</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_13.gif' %}">
                    <p>小小的成绩</p>
                </li>
            </ul>
        </div>

        <div class="bottom_list">
            <div class="bot_left">
                <h5><img src="{% static 'img/common_img/QQ图片20160909175522_22.gif' %}"></h5>
                <div class="left_con">
                    <h3>服务热线：</h3>
                    <p>400-888-9200<span>（免长途费）</span></p>
                    <i>023-65584888</i>
                    <em>工作时间：9：00-21：00</em>
                </div>
            </div>
            <div class="bot_right">
                <ul class="list_right">
                    <li>
                        <h2>支付方式</h2>
                        <div class="con_list">
                            <a href="#">货到付款</a>
                            <a href="#">余额支付</a>
                            <a href="#">银行转账</a>
                            <a href="#">在线支付</a>
                        </div>
                    </li>
                    <li>
                        <h2>配送方式</h2>
                        <div class="con_list">
                            <a href="#">E宠快递</a>
                            <a href="#">外包快递</a>
                            <a href="#">物流运输</a>
                            <a href="#">公司地址</a>
                        </div>
                    </li>
                    <li>
                        <h2>购物指南</h2>
                        <div class="con_list">
                            <a href="#">退换货政策</a>
                            <a href="#">它时尚杂志</a>
                            <a href="#">常见问题</a>
                            <a href="#">宠物知识</a>
                        </div>
                    </li>
                    <li>
                        <h2>关于我们</h2>
                        <div class="con_list">
                            <a href="#">关于我们</a>
                            <a href="#">仓储中心</a>
                            <a href="#">联系我们</a>
                            <a href="#">人才招聘</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="footer_mid">
    <div class="footer_midcon">
        <div class="mid_left">
            <div class="safe">
							<span>
								<i></i>
								<h5>安全认证</h5>
								<b></b>
							</span>
            </div>
            <div class="safeSite">
                <img src="{% static 'img/common_img/safe360.png' %}">
                <img src="{% static 'img/common_img/bottom_small_img.png' %}">
                <img src="{% static 'img/common_img/safegs.png' %}">
                <img src="{% static 'img/common_img/safeqq.png' %}">
                <img src="{% static 'img/common_img/safesite.png' %}">
                <img src="{% static 'img/common_img/safetrace.png' %}">

            </div>
        </div>
        <div class="mid_center">
            <div class="two-code1">
                <p>扫描或点击下载手机版</p>
                <img src="{% static 'img/common_img/QQ图片20160909175522_26.gif' %}">
            </div>
            <div class="two-code2">
                <p>扫描或点击下载手机版</p>
                <img src="{% static 'img/common_img/QQ图片20160909175522_26.gif' %}">
            </div>
        </div>
        <div class="mid_right">
            <div class="honour">
							<span>
								<i></i>
								<h5>荣誉奖章</h5>
								<b></b>
							</span>
            </div>
            <div class="honourSite">
                <img src="{% static 'img/common_img/ebrun.png' %}">
                <img src="{% static 'img/common_img/wsxh.png' %}">
                <img src="{% static 'img/common_img/cqsywyh.png' %}">
                <img src="{% static 'img/common_img/goodNet.png' %}">
                <img src="{% static 'img/common_img/cqsapa.png' %}">
                <img src="{% static 'img/common_img/sjws.png' %}">

            </div>
        </div>
    </div>
</div>

<div class="footer_bottom">
    <p>渝ICP13005525号-2 &nbsp;&nbsp; 渝ICP备10002905 &nbsp;&nbsp;&nbsp; 增值电信业务经营许可证：渝B2-20140042 &nbsp;&nbsp; Copyright
        ©&nbsp; 2007-2016epet.com&nbsp; &nbsp;重庆易宠科技有限公司</p>
</div>

<!--尾部结束-->
</body>
</html>

templates/goods.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title></title>
    <link rel="stylesheet" href="{% static 'css/common.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/goods.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/goods.js' %}"></script>
</head>
<body>


<!--头部开始-->
<div class="header">
    <div class="header_con">
        <div class="header_left">
		 			<span>
			 			<a href="#" class="header_a">E宠就是正品</a>
			 			<i>评价(<a href="#">389.4万</a>)</i>
		 		    </span>
        </div>
        <div class="header_right">
            <ul>
                <li></li>
                <li><a href="{% url 'app:shopcar' %}">购物车</a></li>
                <li id="mypet">
                    <a href="#">我的E宠<img src="{% static 'img/common_img/h5.gif' %}"></a>
                    <div class="mypet">
                        <a href="#">我的订单 </a>
                        <a href="#">充值得到优惠</a>
                        <a href="#">兑换现金劵</a>
                        <a href="#">推荐得惊喜</a>
                    </div>
                </li>
                <li id="mycollect">
                    <a href="#">收藏我 <img src="{% static 'img/common_img/h5.gif' %}"></a>
                    <div class="mycollect">
                        <input value="加入收藏夹" class="join" type="button">
                        <input value="保存到桌面" class="save" type="button">
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!--头部结束-->
<!--首部开始-->
<div class="head_htop">
    <div class="headtop_tcon">
        <div class="tcon_top">
            <h3><img src="{% static 'img/homepage/QQ图片20160909171624_23.gif' %}"></h3>
            <div class="form">
						<span>
							<input class="input" type="text">
						    <input value="搜索" class="btn" type="button">
						</span>
                <div class="nav">
                    <p>热门搜索：<span>进口大聚惠</span></p>
                    <h6>
                        <ul>
                            <li><a href="#">比瑞吉</a></li>
                            <li><a href="#">冠军犬 佰芙粮</a></li>
                            <li><a href="#">巅峰</a></li>
                            <li><a href="#">顽皮买一赠一</a></li>
                        </ul>
                    </h6>
                </div>
            </div>
            <h5>
                <img src="{% static 'img/homepage/QQ图片20160909171624_26.gif' %}">
                <i>400-888-9200</i>
            </h5>
            <h4>
                <img src="{% static 'img/homepage/shopping-cart.gif' %}">
                <a href="{% url 'app:shopcar' %}">购物车（<b>{{ carts_num }}</b>）</a>
            </h4>
        </div>

        <div class="tcon_bottom">
            <div class="bottom_left" id="abc">
                <ul>
                    <li class="dog"><a href="#">狗狗<b></b></a></li>
                    <li class="sort"><a href="#">商品分类<b></b></a></li>
                </ul>
            </div>


            <div class="bottom_center">
                <ul>
                    <li><a href="#">全球特卖</a></li>
                    <li><a href="#">国家馆<b></b></a></li>
                    <li><a href="#">热卖礼包 <b></b></a></li>
                    <li><a href="#">清仓特价<b></b></a></li>
                </ul>
            </div>
            <div class="bottom_right">
                <img src="{% static 'img/homepage/phoneApp.gif' %}">
            </div>
        </div>
    </div>
</div>

<!--商品详情-->
<div class="goods_con con">
    <div class="goods_main">
        <div class="goods_list">
            <div class="list_ul  list">
                <ul>
                    <li class="doglist">
                        <a href="#">狗狗9132</a>
                        <i></i>
                        <div class="list_li1 tab">
                            <a href="#">狗狗 <span>1345</span></a>
                            <a href="#">狗狗 <span>1345</span></a>

                        </div>
                    </li>
                    <li class="dogeat">
                        <a href="#">狗狗零食1832</a>
                        <i></i>
                        <div class="list_li2 tab">
                            <a href="#">狗狗 <span>1345</span></a>
                            <a href="#">狗狗 <span>1345</span></a>
                            <a href="#">狗狗 <span>1345</span></a>
                            <a href="#">狗狗 <span>1345</span></a>
                        </div>
                    </li>
                    <li class="dogfood">
                        <a href="#">肉制零食4722</a>
                        <i></i>
                        <div class="list_li3 tab">

                            <a href="#">狗狗 <span>1345</span></a>
                            <a href="#">狗狗 <span>1345</span></a>
                            <a href="#">狗狗 <span>1345</span></a>

                        </div>
                    </li>
                </ul>
            </div>
            <div calss="goodsdaily">
                <p>商品详情</p>
            </div>
        </div>

        <!--//放大镜-->
        <div class="goodscar">
            <div class="glass">
                <div id="smallImg" bgimg="{{ t_goods.img_src }}">
                    <div id="smallArea" style="width: 100px; height: 100px;"></div>
                </div>

                <div class="img_list">
                    <img src="{{ t_goods.img_src }}"
                         class="goodsImg">
                    <img src="{{ t_goods.img_src }}">
                    <img src="{{ t_goods.img_src }}">
                    <img src="{{ t_goods.img_src }}">
                </div>
                <div class="enjoin">
                    {{ t_goods.longname }}
                </div>
            </div>


            <div class="info">
                <div id="bigArea" style="">
                    <img id="bigImg" src="{% static 'img/goods/1726c8e64575c7ee8e87168120d59479_看图王.jpg' %}">
                </div>
                <div class="info_con">
                    <h3 class="goodsName">{{ t_goods.longname }} </h3>
                    <div class="price">
                        <div class="pre_price">
                            <span>市面价：</span>
                            <i class="goodsPrice">{{ t_goods.price }}</i>
                        </div>
                        <div class="now_price">
                            <span>E宠价：</span>
                            <i>{{ t_goods.low_price }}</i>
                        </div>
                    </div>

                    <div class="goods_num">
                        <div class="num1"><span>编号：</span>1323</div>
                        <div class="num1"><span>已售：</span>17个</div>
                        <div class="num1"><span>赠送：</span>最多赠送8E宠币</div>
                        <div class="num1">
                            <span>互动：</span>
                            <a href="#">查看评价<i>(11)</i></a>
                            <a href="#">咨询<i>(1)</i></a>
                        </div>
                    </div>

                    <div class="orange_list">
                        <ul>
                            <li>正品溯源</li>
                            <li>全球精选</li>
                            <li>自营快递</li>
                            <li>自营大仓</li>
                        </ul>
                    </div>

                    <div class="size">
                        <div class="buy">
                            <span>我要买：</span>
                            <div class="minu">-</div>
                            <b class="num">1</b>
                            <div class="add">+</div>
                            个
                        </div>
                    </div>
                    <div class="order">
                        <span>E宠快递15点前下单，其他快递16点前下单，当天发货。</span>
                        <a href="#">运费详情&gt;&gt;</a>
                    </div>

                    <div class="car_btn">
                        <input value="加入购物车" class="addCart" type="button" goodsid="{{ t_goods.id }}">
                        <a href="#"><i></i>咨询</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!--尾部开始-->
<div class="footer_mid">
    <div class="footer_midcon">
        <div class="mid_left">
            <div class="safe">
							<span>
								<i></i>
								<h5>安全认证</h5>
								<b></b>
							</span>
            </div>
            <div class="safeSite">
                <img src="{% static 'img/common_img/safe360.png' %}">
                <img src="{% static 'img/common_img/bottom_small_img.png' %}">
                <img src="{% static 'img/common_img/safegs.png' %}">
                <img src="{% static 'img/common_img/safeqq.png' %}">
                <img src="{% static 'img/common_img/safesite.png' %}">
                <img src="{% static 'img/common_img/safetrace.png' %}">

            </div>
        </div>
        <div class="mid_center">
            <div class="two-code1">
                <p>扫描或点击下载手机版</p>
                <img src="{% static 'img/common_img/QQ图片20160909175522_26.gif' %}">
            </div>
            <div class="two-code2">
                <p>扫描或点击下载手机版</p>
                <img src="{% static 'img/common_img/QQ图片20160909175522_26.gif' %}">
            </div>
        </div>
        <div class="mid_right">
            <div class="honour">
							<span>
								<i></i>
								<h5>荣誉奖章</h5>
								<b></b>
							</span>
            </div>
            <div class="honourSite">
                <img src="{% static 'img/common_img/ebrun.png' %}">
                <img src="{% static 'img/common_img/wsxh.png' %}">
                <img src="{% static 'img/common_img/cqsywyh.png' %}">
                <img src="{% static 'img/common_img/goodNet.png' %}">
                <img src="{% static 'img/common_img/cqsapa.png' %}">
                <img src="{% static 'img/common_img/sjws.png' %}">

            </div>
        </div>
    </div>
</div>
<div class="footer_bottom">
    <p>渝ICP13005525号-2 &nbsp;&nbsp; 渝ICP备10002905 &nbsp;&nbsp;&nbsp; 增值电信业务经营许可证：渝B2-20140042 &nbsp;&nbsp; Copyright ©&nbsp;
        2007-2016epet.com&nbsp; &nbsp;重庆易宠科技有限公司</p>
</div>
<!--尾部结束-->
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
</head>
<body>
<div class="login_head">
    <div class="loginh_con">
        <div class="loginh_left">
            <img src="{% static 'img/register/QQ图片20160909171624_23.gif' %}"/>
        </div>
        <div class="loginh_right">
            <ul>
                <li><a href="{% url 'app:homepage' %}">E宠商城</a></li>
                <li><a href="#">活动</a></li>
                <li><a href="#">品牌</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="login_middle">
    <div class="login">
        <div class="login_con">
            <div class="login_main">
                <div class="login_tab">
                    <div class="method">
                        <span>普通登录</span>
                    </div>
                </div>
                <form action="{% url 'app:login' %}" method="post">
                    {% csrf_token %}
                    <div class="login_input">
                        <div class="tel">
                            <span></span>
                            <input type="text" placeholder="手机号" name="tel"/>
                        </div>
                        <div class="passwd">
                            <span></span>
                            <input type="password" placeholder="密码" name="password"/>
                        </div>
                    </div>
                    <div class="check">
							<span>
								<input type="checkbox" name="auto" required="required"/>
								<i>自动登录</i>
							</span>
                        <a href="#">忘记密码?</a>
                    </div>
                    <div class="btn">
                        <input type="submit" value="登录" required="required"/>
                    </div>
                </form>

                <div class="link">
							<span>
								<h5>合作网站登录：</h5>
								<img src="{% static 'img/register/QQ截图20160920134847.png' %}"/>
							</span>

                    <a href="{% url 'app:register' %}">注册账号</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="login_footer">
    <div class="footer_list">
        <ul>
            <li><a href="#">E宠商城</a></li>
            <li><a href="#">淘宝</a></li>
            <li><a href="#">知识</a></li>
            <li><a href="#">联系我们</a></li>
            <li><a href="#">关于我们</a></li>
            <li><a href="#">游戏</a></li>
        </ul>
        <p>渝ICP备13005525号-2 渝ICP备 10002905 增值电信业务经营许可证：渝B2-20140042 Copyright &copy; 2007-2016 epet.com 重庆易宠科技有限公司</p>
    </div>
</div>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/jquery.idcode.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.idcode.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/register.js' %}"></script>
</head>
<body>
<div class="register_head">
    <div class="registerh_con">
        <div class="registerhc_left">
            <span class="logo"><a href="{% url 'app:homepage' %}"><img src="{% static 'img/register/QQ图片20160909171624_23.gif' %}"/></a></span>
            <span class="register"><img src="{% static 'img/register/welcome_07.jpg' %}"/>	</span>
        </div>
        <div class="registerhc_right">
					<span>
						<i>已有账号?</i>
						<a href="{% url 'app:login' %}">登录</a>
					</span>
        </div>
    </div>
</div>

<div class="register_middle">
    <div class="registerm_con">
        <div class="login">
            <form action="{% url 'app:register' %}" method="post">
                {% csrf_token %}
                <div class="text" id="tel">
                    <span>手机号：</span>
                    <input type="text" placeholder="请输入手机号码" name="tel"/>
                    <em class="right1"><img src="{% static 'img/register/ok_03.jpg' %}"/></em>
                    <i class="right1_num">请输入11位电话号码</i>
                </div>
                <div class="text" id="txtVerification">
                    <span>验证码：</span>
                    <input type="text" id="Txtidcode" placeholder="区分大小写"><span id="idcode"></span>
                    <input type="button" class="btn" value="换一换"/>
                    <em class="right2"><img src="{% static 'img/register/ok_03.jpg' %}"/></em>
                    <i class="right2_num">请输入4位验证码</i>
                </div>
                <div class="text" id="user">
                    <span>用户名：</span>
                    <input type="text" placeholder="用户名" name="username"/>
                    <em class="right4"><img src="{% static 'img/register/ok_03.jpg' %}"/></em>
                    <i class="right4_num">请输入4-20位用户名</i>
                </div>
                <div class="text" id="password">
                    <span>密码：</span>
                    <input type="password" placeholder="密码（6-12位）" name="password"/>
                    <em class="right5"><img src="{% static 'img/register/ok_03.jpg' %}"/></em>
                    <i class="right5_num">请输入8-20位密码</i>
                    <ul>
                        <li class="rank1">弱</li>
                        <li class="rank2">中</li>
                        <li class="rank3">强</li>
                    </ul>
                </div>
                <div class="text" id="passwd">
                    <span>确认密码：</span>
                    <input type="password" placeholder="确认密码"/>
                    <em class="right6"><img src="{% static 'img/register/ok_03.jpg' %}"/></em>
                    <i class="right6_num">请输入确认密码</i>
                </div>
                <div class="allow">
                    <span><input type="checkbox"/><i> 我已阅读并接受E宠</i><a href="#">《用户使用协议》</a></span>
                </div>
                <div class="button">
                    <input type="submit" value="立即注册"/>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="registery_footer">
    <div class="footer_list">
        <ul>
            <li><a href="#">E宠商城</a></li>
            <li><a href="#">淘宝</a></li>
            <li><a href="#">知识</a></li>
            <li><a href="#">联系我们</a></li>
            <li><a href="#">关于我们</a></li>
            <li><a href="#">游戏</a></li>
        </ul>
        <p>渝ICP备13005525号-2 渝ICP备 10002905 增值电信业务经营许可证：渝B2-20140042 Copyright &copy; 2007-2016 epet.com 重庆易宠科技有限公司</p>
    </div>
</div>

</body>
</html>

templates/shopcar.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title></title>
    <link rel="stylesheet" href="{% static 'css/common.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/shopcar.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/shopcar.js' %}"></script>

</head>
<body>

<!--头部开始-->
<div class="header">
    <div class="header_con">
        <div class="header_left">
		 			<span>
			 			<a href="#" class="header_a">E宠就是正品</a>
			 			<i>评价(<a href="#">389.4万</a>)</i>
		 		    </span>
        </div>
        <div class="header_right">
            <ul>
                <li>
                    {% if token %}
                        {{ user.username }}
                    {% endif %}
                </li>
                <li><a href="{% url 'app:login' %}">[登录]</a></li>
                <li><a href="{% url 'app:register' %}">[注册]</a></li>
                <li><a href="{% url 'app:shopcar' %}">购物车</a></li>
                <li id="mypet">
                    <a href="#">我的E宠<img src="{% static 'img/common_img/h5.gif' %}"></a>
                    <div class="mypet">
                        <a href="#">我的订单 </a>
                        <a href="#">充值得到优惠</a>
                        <a href="#">兑换现金劵</a>
                        <a href="#">推荐得惊喜</a>
                    </div>
                </li>
                <li id="mycollect">
                    <a href="#">收藏我 <img src="{% static 'img/common_img/h5.gif' %}"></a>
                    <div class="mycollect">
                        <input value="加入收藏夹" class="join" type="button">
                        <input value="保存到桌面" class="save" type="button">
                    </div>
                </li>
                <li><a href="{% url 'app:homepage' %}">继续添加商品</a></li>
            </ul>
        </div>
    </div>
</div>
<!--头部结束-->

<div class="shopcar">
    <div class="shopcar_con">
        <div class="head">
            <div class="logo">
                <img src="{% static 'img/shopcar/cart-logo.png' %}">
                <span>购物车</span>
            </div>
            <div class="search">
                <input class="searchinput" type="text">
                <input value="搜索" class="searchbtn" type="button">
            </div>
            <div class="shopcar_nav">
                <a href="#">购物车<b>?</b></a>
                <a href="#">我的收藏<b>?</b></a>
                <a href="#">我购买过<b>?</b></a>
                <a href="#">最近浏览<b>?</b></a>
            </div>
        </div>
        <div class="shopcar_main">
            <div class="title">
                <em>西部大仓</em>
                <b></b>
                <div class="mail">
                    <span></span>
                    订单已包邮（顺丰、EMS不包邮）
                </div>
            </div>

            <div class="shopcar_list">
                <ul class="list_ul">
                    {% for cart in carts %}
                        <li class="goods">
                            <div class="checkAll">
                                {% if cart.isselect %}
                                    <div class="click bt" cartid="{{ cart.id }}" isselect="{{ cart.isselect }}"></div>
                                {% else %}
                                    <div class="no bt" cartid="{{ cart.id }}" isselect="{{ cart.isselect }}"></div>
                                {% endif %}
                            </div>
                            <div class="picture">
                                <h1>
                                    <img src="{{ cart.goods.img_src }}">
                                </h1>
                                <p>{{ cart.goods.longname }}</p></div>
                            <div class="num">
                                <b class="sub" goodsid="{{ cart.goods.id }}">-</b>
                                <span number="{{ cart.number }}">x{{ cart.number }}</span>
                                <i class="add" goodsid="{{ cart.goods.id }}">+</i>
                            </div>
                            <div class="price" price="{{ cart.goods.low_price }}">{{ cart.goods.low_price }}<span>{{ cart.goods.price }}/件</span></div>
                            <div class="remove" goodsid="{{ cart.goods_id }}"><b class="removecookie">[删除]</b></div>
                        </li>
                    {% endfor %}

                </ul>
            </div>

            <div class="account">
                <div class="removeAll">
                    <div class="qx" isselect="false"></div>
                    <i>全选</i>
                </div>
                <div class="total">
                    <span>总价（不含运费）:</span>
                    ￥<h5>324.00</h5>
                    <div class="count">
                        去结算
                        <i></i>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


<!--尾部开始-->
<div class="footer_bottom">
    <p>渝ICP13005525号-2 &nbsp;&nbsp; 渝ICP备10002905 &nbsp;&nbsp;&nbsp; 增值电信业务经营许可证：渝B2-20140042 &nbsp;&nbsp; Copyright
        ©&nbsp; 2007-2016epet.com&nbsp; &nbsp;重庆易宠科技有限公司</p>
</div>
<!--尾部结束-->
</body>
</html>